Repository dotkom/onlineweb4, pull requests merged in 2019-10, with the labels that each got.

#2341 Set proper NTNU Username for employees
  apps/dataporten/settings.py
  apps/dataporten/views.py
Labels: Type: Bug

#2356 Use ResponsiveImage for Offline thumbnail
  apps/gallery/settings.py
  apps/gallery/util.py
  apps/offline/migrations/0004_issue_image.py
  apps/offline/models.py
  apps/offline/serializers.py
  apps/offline/signals.py
  apps/offline/tasks.py
  apps/offline/tests.py
  apps/offline/utils.py
  assets/frontpage/OfflineWidget.js
  requirements-prod.txt
  requirements.txt
  templates/offline/offline.html
Labels: Package: Offline, Type: Code Quality, Type: Enhancement, Type: Refactor

#2382 Set study year to third year on bachelor extension
  apps/dataporten/study/tests/data/3rd_grader_extended_1_year_2018.json
  apps/dataporten/study/tests/utils_tests.py
  apps/dataporten/study/utils.py
Labels: Package: Authentication, Priority: Medium
