Repository dotkom/onlineweb4, pull requests merged in 2019-08, with the labels that each got.

#2280 Add API for Webshop
  apps/payment/models.py
  apps/payment/serializers.py
  apps/webshop/__init__.py
  apps/webshop/appconfig.py
  apps/webshop/models.py
  apps/webshop/serializers.py
  apps/webshop/signals.py
  apps/webshop/tests/__init__.py
  apps/webshop/tests/api_tests.py
  apps/webshop/tests/view_tests.py
  apps/webshop/urls.py
  apps/webshop/views.py
Labels: Package: Webshop, Priority: Medium, Status: Review Needed, Type: Feature

#2294 Use OnlineGroup email as event organizer email
  apps/events/models.py
  apps/feedback/tests.py
Labels: #1209

#2312 Simple upgrade dependencies
  requirements-linting.txt
  requirements-prod.txt
  requirements-testing.txt
  requirements.txt
Labels: dependencies
